[general]
RemoteNickFormat="{NICK}@{BRIDGE}: "

#[slack.example]
##Token to connect with the Slack API
##You'll have to use a test/api-token using a dedicated user and not a bot token.
##See https://github.com/42wim/matterbridge/wiki/Slack-bot-setup for more information
#Token="${SLACK_EXAMPLE_TOKEN}" # real user

[slack.archivers]
Token="${SLACK_ARCHIVERS_TOKEN}" # real user

[slack.betanyc]
Token="${SLACK_BETANYC_TOKEN}" # real user: bridgebot-patcon

[slack.civictechto]
Token="${SLACK_CIVICTECHTO_TOKEN}" # bot user

[slack.diybioto]
Token="${SLACK_DIYBIOTO_TOKEN}" # TMP patcon user
RemoteNickFormat="{NICK}@{BRIDGE}.{PROTOCOL} "

[slack.edgi]
Token="${SLACK_EDGI_TOKEN}" # real user

[slack.g0v-tw]
Token="${SLACK_G0VTW_TOKEN}" # real user: bridgebot-patcon

[slack.hacklabto]
Token="${SLACK_HACKLABTO_TOKEN}" # bot user
RemoteNickFormat="{NICK}@{BRIDGE}.{PROTOCOL} "

[slack.muckrock]
Token="${SLACK_MUCKROCK_TOKEN}" # matterbridge-bot user

[slack.opencollective]
Token="${SLACK_OPENCOLLECTIVE_TOKEN}" # real user

[slack.progressivehacknight]
Token="${SLACK_PROGHACKNIGHT_TOKEN}" # real user: bridgebot-patcon

[telegram.hacklabto]
Token="${TELEGRAM_TOKEN}" # bot user: hacklabto_bridgebot
RemoteNickFormat="{NICK}@{PROTOCOL}: "
UseInsecureURL=true

[gitter.gitter]
Token="${GITTER_HACKLABTO_TOKEN}" # bot user: hacklabto twitter account
RemoteNickFormat="{NICK}@{PROTOCOL}: "

[irc.freenode]
Server="chat.freenode.net:6697"
Nick="${IRC_USERNAME}"
RemoteNickFormat="{NICK}@{PROTOCOL} "
UseTLS=true
UseSASL=true
NickServNick="${IRC_USERNAME}"
NickServPassword="${IRC_PASSWORD}"
IgnoreNicks="doorbot"

[[gateway]]
name="muckrock-canada"
enable=false
  [[gateway.inout]]
  account="slack.civictechto"
  channel="muckrock-canada-pub"
  [[gateway.inout]]
  account="slack.muckrock"
  channel="canada"

[[gateway]]
name="datatogether"
enable=true
  [[gateway.inout]]
  account="slack.edgi"
  channel="datatogether"
  [[gateway.inout]]
  account="slack.archivers"
  channel="datatogether"
  [[gateway.inout]]
  account="gitter.gitter"
  channel="datatogether/lobby"

[[gateway]]
name="community-building"
enable=true
  [[gateway.inout]]
  account="slack.edgi"
  channel="community_building"
  [[gateway.inout]]
  account="slack.archivers"
  channel="community-building"

[[gateway]]
name="webmonitoring"
enable=true
  [[gateway.inout]]
  account="slack.edgi"
  channel="webmonitoring"
  [[gateway.inout]]
  account="slack.archivers"
  channel="webmonitoring"

[[gateway]]
name="oc-edgi"
enable=true
  [[gateway.inout]]
  account="slack.edgi"
  channel="opencollective"
  [[gateway.inout]]
  account="slack.opencollective"
  channel="oc-edgi"

[[gateway]]
name="oc-civictechto"
enable=true
  [[gateway.inout]]
  account="slack.civictechto"
  channel="grants-and-funding"
  [[gateway.inout]]
  account="slack.opencollective"
  channel="oc-civictechto"

## HACKLAB

[[gateway]]
name="hacklabto-general"
enable=true
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel="-1001087615555"
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="general"

[[gateway]]
name="hacklabto-3d-printers"
enable=true
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel="-1001081652474"
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="3d-printers"

[[gateway]]
name="hacklabto-amateur-radio"
enable=false
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel=""
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="amateur_radio"

[[gateway]]
name="hacklabto-diybioto"
enable=true
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel="-1001089003630"
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="biolab"
  [[gateway.inout]]
  account="slack.diybioto"
  channel="general"

[[gateway]]
name="hacklabto-darkroom"
enable=false
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel=""
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="darkroom"

[[gateway]]
name="hacklabto-shop"
enable=true
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel="-1001093582611"
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="shop"

[[gateway]]
name="hacklabto-board"
enable=false
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel=""
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="hacklab-board"

[[gateway]]
name="hacklabto-operations"
enable=true
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel="-1001135498637"
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="operations"

[[gateway]]
name="opencollective-hacklabto"
enable=true
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="opencollective"
  [[gateway.inout]]
  account="slack.opencollective"
  channel="oc-hacklabto"

[[gateway]]
name="irc"
enable=true
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="freenode-irc"
  [[gateway.inout]]
  account="irc.freenode"
  channel="#hacklabto"

[[gateway]]
name="lobby"
enable=true
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="public-lobby"
  [[gateway.inout]]
  account="gitter.gitter"
  channel="hacklabto/lobby"

[[gateway]]
name="vnetwork"
enable=true
  [[gateway.inout]]
  account="slack.civictechto"
  channel="vnetwork"
  [[gateway.inout]]
  account="slack.g0v-tw"
  channel="vnetwork"
  #[[gateway.inout]]
  #account="slack.progressivehacknight"
  #channel="vnetwork"
  [[gateway.inout]]
  account="slack.betanyc"
  channel="vnetwork"

[[gateway]]
name="holopolis"
enable=true
  [[gateway.inout]]
  account="slack.civictechto"
  channel="holopolis"
  [[gateway.inout]]
  account="slack.g0v-tw"
  channel="holopolis"
