[general]
RemoteNickFormat="{NICK} ({CHANNEL}@{BRIDGE})"
TranslationAttribution="g0v translation bridge (translated by Google)"
PreserveThreading=true
ShowUserTyping=true
SyncTopic=false
MediaDownloadSize=1000000
ShowJoinPart=true

[whatsapp.mygroup]
Number="+919249701001"
SessionFile="session-9249701001.gob"
QrOnWhiteTerminal=false
RemoteNickFormat="[{PROTOCOL}] @{NICK}: "

[telegram.mygroup]
Token="1318928080:AAEJ8W43gCiKTTRUv1YbX8nkZFTT-S1GhLw"
Server="mark"
RemoteNickFormat="({PROTOCOL}) @{NICK} "
MessageFormat="HTMLNick"
QuoteFormat="{MESSAGE} (re @{QUOTENICK}: {QUOTEMESSAGE})"

[[gateway]]
name="gateway2"
enable=true

[[gateway.inout]]
account="whatsapp.mygroup"
channel="919562348796-1534694267@g.us"

[[gateway.inout]]
account="telegram.mygroup"
channel="-1001544659730"
