[slack.edgi]
#Token to connect with the Slack API
#You'll have to use a test/api-token using a dedicated user and not a bot token.
#See https://github.com/42wim/matterbridge/wiki/Slack-bot-setup for more information
Token="${SLACK_EDGI_TOKEN}" # real user
RemoteNickFormat="{NICK}@{BRIDGE} "

[slack.archivers]
#Token to connect with the Slack API
#You'll have to use a test/api-token using a dedicated user and not a bot token.
#See https://github.com/42wim/matterbridge/wiki/Slack-bot-setup for more information
Token="${SLACK_ARCHIVERS_TOKEN}" # real user
RemoteNickFormat="{NICK}@{BRIDGE} "

[slack.civictechto]
Token="${SLACK_CIVICTECHTO_TOKEN}" # bot user
RemoteNickFormat="{NICK}@{BRIDGE} "

[slack.opencollective]
Token="${SLACK_OPENCOLLECTIVE_TOKEN}" # real user
RemoteNickFormat="{NICK}@{BRIDGE} "

[slack.hacklabto]
Token="${SLACK_HACKLABTO_TOKEN}" # bot user
RemoteNickFormat="{NICK}@{BRIDGE}.{PROTOCOL} "

[slack.diybioto]
Token="${SLACK_DIYBIOTO_TOKEN}" # TMP patcon user
RemoteNickFormat="{NICK}@{BRIDGE}.{PROTOCOL} "

[telegram.hacklabto]
Token="${TELEGRAM_TOKEN}" # bot user: hacklabto_bridgebot
RemoteNickFormat="{NICK}@{PROTOCOL}: "

[irc.freenode]
Server="chat.freenode.net:6697"
Nick="${IRC_USERNAME}"
RemoteNickFormat="{NICK}@{PROTOCOL} "
UseTLS=true
UseSASL=true
NickServNick="${IRC_USERNAME}"
NickServPassword="${IRC_PASSWORD}"
IgnoreNicks="doorbot"

[[gateway]]
name="datatogether"
enable=true
  [[gateway.inout]]
  account="slack.edgi"
  channel="datatogether"
  [[gateway.inout]]
  account="slack.archivers"
  channel="datatogether"

[[gateway]]
name="community-building"
enable=true
  [[gateway.inout]]
  account="slack.edgi"
  channel="community_building"
  [[gateway.inout]]
  account="slack.archivers"
  channel="community-building"

[[gateway]]
name="webmonitoring"
enable=true
  [[gateway.inout]]
  account="slack.edgi"
  channel="webmonitoring"
  [[gateway.inout]]
  account="slack.archivers"
  channel="webmonitoring"

[[gateway]]
name="oc-edgi"
enable=true
  [[gateway.inout]]
  account="slack.edgi"
  channel="opencollective"
  [[gateway.inout]]
  account="slack.opencollective"
  channel="oc-edgi"

[[gateway]]
name="oc-civictechto"
enable=true
  [[gateway.inout]]
  account="slack.civictechto"
  channel="grants-and-funding"
  [[gateway.inout]]
  account="slack.opencollective"
  channel="oc-civictechto"

## HACKLAB

[[gateway]]
name="hacklabto-general"
enable=true
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel="-1001087615555"
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="general"

[[gateway]]
name="hacklabto-3d-printers"
enable=true
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel="-1001081652474"
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="3d-printers"

[[gateway]]
name="hacklabto-amateur-radio"
enable=false
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel=""
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="amateur_radio"

[[gateway]]
name="hacklabto-diybioto"
enable=true
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel="-1001089003630"
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="biolab"
  [[gateway.inout]]
  account="slack.diybioto"
  channel="general"

[[gateway]]
name="hacklabto-darkroom"
enable=false
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel=""
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="darkroom"

[[gateway]]
name="hacklabto-shop"
enable=true
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel="-1001093582611"
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="shop"

[[gateway]]
name="hacklabto-board"
enable=false
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel=""
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="hacklab-board"

[[gateway]]
name="hacklabto-operations"
enable=false
  [[gateway.inout]]
  account="telegram.hacklabto"
  channel=""
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="operations"

[[gateway]]
name="opencollective-hacklabto"
enable=true
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="opencollective"
  [[gateway.inout]]
  account="slack.opencollective"
  channel="oc-hacklabto"

[[gateway]]
name="irc"
enable=true
  [[gateway.inout]]
  account="slack.hacklabto"
  channel="freenode-irc"
  [[gateway.inout]]
  account="irc.freenode"
  channel="#hacklabto"
