[general]
RemoteNickFormat="{NICK} (#{CHANNEL}@{BRIDGE}): "
# Show messages announcing when people arrive/leave remote channels

#[slack.example]
##Token to connect with the Slack API
##You'll have to use a test/api-token using a dedicated user and not a bot token.
##See https://github.com/42wim/matterbridge/wiki/Slack-bot-setup for more information
#Token="${SLACK_EXAMPLE_TOKEN}" # real user

[slack.civictechto]
Token="${SLACK_CIVICTECHTO_TOKEN}" # bot user
ShowJoinPart=true

[slack.g0v-tw]
Token="${SLACK_G0VTW_TOKEN}" # real user: bridgebot-patcon
ShowJoinPart=true

[[gateway]]
name="tech-workers-coop"
enable=true
  [[gateway.inout]]
  account="slack.g0v-tw"
  channel="twc-g0v"
    [gateway.inout.options]
    locale="zh-TW"
  [[gateway.inout]]
  account="slack.g0v-tw"
  channel="twc-g0v-en"
    [gateway.inout.options]
    locale="en"

[[gateway]]
name="vtaiwan"
enable=true
  [[gateway.inout]]
  account="slack.g0v-tw"
  channel="vtaiwan"
    [gateway.inout.options]
    locale="zh-TW"
  [[gateway.inout]]
  account="slack.g0v-tw"
  channel="vtaiwan-en"
    [gateway.inout.options]
    locale="en"
  [[gateway.inout]]
  account="slack.civictechto"
  channel="vtaiwan"
    [gateway.inout.options]
    locale="en"


[[gateway]]
name="i18n-test"
enable=true
  [[gateway.inout]]
  account="slack.g0v-tw"
  channel="i18n-test-tw"
    [gateway.inout.options]
    locale="zh-TW"
  [[gateway.inout]]
  account="slack.g0v-tw"
  channel="i18n-test-en"
    [gateway.inout.options]
    locale="en"

[[gateway]]
name="general"
enable=true
  [[gateway.in]]
  account="slack.g0v-tw"
  channel="general"
    [gateway.in.options]
    locale="zh-TW"
  [[gateway.out]]
  account="slack.g0v-tw"
  channel="general-en"
    [gateway.out.options]
    locale="en"
