[general]
RemoteNickFormat="{NICK}@{BRIDGE}"

[slack.edgi]
#Token to connect with the Slack API
#You'll have to use a test/api-token using a dedicated user and not a bot token.
#See https://github.com/42wim/matterbridge/wiki/Slack-bot-setup for more information
Token="${SLACK_EDGI_TOKEN}"

[slack.archivers]
#Token to connect with the Slack API
#You'll have to use a test/api-token using a dedicated user and not a bot token.
#See https://github.com/42wim/matterbridge/wiki/Slack-bot-setup for more information
Token="${SLACK_ARCHIVERS_TOKEN}"

[[gateway]]
name="testing"
enable=true
  [[gateway.inout]]
  account="slack.edgi"
  channel="testing"
  [[gateway.inout]]
  account="slack.archivers"
  channel="testing"

#[[gateway]]
#name="datatogether"
#enable=true
#  [[gateway.inout]]
#  account="slack.edgi"
#  channel="datatogether"
#  [[gateway.inout]]
#  account="slack.archivers"
#  channel="datatogether"
#
#[[gateway]]
#name="community-building"
#enable=true
#  [[gateway.inout]]
#  account="slack.edgi"
#  channel="community_building"
#  [[gateway.inout]]
#  account="slack.archivers"
#  channel="community-building"
#
#[[gateway]]
#name="webmonitoring"
#enable=true
#  [[gateway.inout]]
#  account="slack.edgi"
#  channel="webmonitoring"
#  [[gateway.inout]]
#  account="slack.archivers"
#  channel="webmonitoring"

